["github.com/codahale/rfc6979"]
  sumVersion = "v0.0.0-20141003034818-6a90f24967eb"
  ["github.com/codahale/rfc6979".fetch]
    type = "git"
    url = "https://github.com/codahale/rfc6979"
    rev = "6a90f24967ebb1aa57b22f74a13dbb3faad8cf3d"
    sha256 = "07p51hmvvzvn84mg1c3kmp799j7jf7w15770qw8qz9q7j8frx03f"

["github.com/creack/pty"]
  sumVersion = "v1.1.9"
  ["github.com/creack/pty".fetch]
    type = "git"
    url = "https://github.com/creack/pty"
    rev = "3a6a957789163cacdfe0e291617a1c8e80612c11"
    sha256 = "1v52599qq76dwq742mffakzj6mxqqccv2szn3hjicjld56nmd2d3"

["github.com/davecgh/go-spew"]
  sumVersion = "v1.1.1"
  ["github.com/davecgh/go-spew".fetch]
    type = "git"
    url = "https://github.com/davecgh/go-spew"
    rev = "8991bc29aa16c548c550c7ff78260e27b9ab7c73"
    sha256 = "0hka6hmyvp701adzag2g26cxdj47g21x6jz4sc6jjz1mn59d474y"

["github.com/dustin/go-humanize"]
  sumVersion = "v1.0.0"
  ["github.com/dustin/go-humanize".fetch]
    type = "git"
    url = "https://github.com/dustin/go-humanize"
    rev = "9f541cc9db5d55bce703bd99987c9d5cb8eea45e"
    sha256 = "1kqf1kavdyvjk7f8kx62pnm7fbypn9z1vbf8v2qdh3y7z7a0cbl3"

["github.com/flynn/go-docopt"]
  sumVersion = "v0.0.0-20140912013429-f6dd2ebbb31e"
  ["github.com/flynn/go-docopt".fetch]
    type = "git"
    url = "https://github.com/flynn/go-docopt"
    rev = "f6dd2ebbb31e9721c860cf1faf5c944aa73e3844"
    sha256 = "07s8fvnab40mcfmlsgrrddgvrirgm1krb7kaqgipcikjcmj8j6ql"

["github.com/fsnotify/fsnotify"]
  sumVersion = "v1.4.9"
  ["github.com/fsnotify/fsnotify".fetch]
    type = "git"
    url = "https://github.com/fsnotify/fsnotify"
    rev = "45d7d09e39ef4ac08d493309fa031790c15bfe8a"
    sha256 = "1i1r72knpbfwwql9frn9bqc3nhfc2ai5m6qllcyr6wban62lr40x"

["github.com/golang/protobuf"]
  sumVersion = "v1.4.2"
  ["github.com/golang/protobuf".fetch]
    type = "git"
    url = "https://github.com/golang/protobuf"
    rev = "d04d7b157bb510b1e0c10132224b616ac0e26b17"
    sha256 = "0m5z81im4nsyfgarjhppayk4hqnrwswr3nix9mj8pff8x9jvcjqw"

["github.com/golang/snappy"]
  sumVersion = "v0.0.4"
  ["github.com/golang/snappy".fetch]
    type = "git"
    url = "https://github.com/golang/snappy"
    rev = "544b4180ac705b7605231d4a4550a1acb22a19fe"
    sha256 = "004cw699yz3pdpawhjhpa0y94c4w479nw1rf39zj6h6027kpwv2j"

["github.com/google/go-cmp"]
  sumVersion = "v0.4.0"
  ["github.com/google/go-cmp".fetch]
    type = "git"
    url = "https://github.com/google/go-cmp"
    rev = "5a6f75716e1203a923a78c9efb94089d857df0f6"
    sha256 = "1x5pvl3fb5sbyng7i34431xycnhmx8xx94gq2n19g6p0vz68z2v2"

["github.com/hpcloud/tail"]
  sumVersion = "v1.0.0"
  ["github.com/hpcloud/tail".fetch]
    type = "git"
    url = "https://github.com/hpcloud/tail"
    rev = "a30252cb686a21eb2d0b98132633053ec2f7f1e5"
    sha256 = "1njpzc0pi1acg5zx9y6vj9xi6ksbsc5d387rd6904hy6rh2m6kn0"

["github.com/kr/pretty"]
  sumVersion = "v0.2.1"
  ["github.com/kr/pretty".fetch]
    type = "git"
    url = "https://github.com/kr/pretty"
    rev = "ead452280cd055b2ae8a7f0db5eb37a878d902f7"
    sha256 = "0vzfz06y9q8gs2nxx0kys0591vzp78k0fvpb8digi5n15h3b25hy"

["github.com/kr/pty"]
  sumVersion = "v1.1.1"
  ["github.com/kr/pty".fetch]
    type = "git"
    url = "https://github.com/kr/pty"
    rev = "282ce0e5322c82529687d609ee670fac7c7d917c"
    sha256 = "0383f0mb9kqjvncqrfpidsf8y6ns5zlrc91c6a74xpyxjwvzl2y6"

["github.com/kr/text"]
  sumVersion = "v0.2.0"
  ["github.com/kr/text".fetch]
    type = "git"
    url = "https://github.com/kr/text"
    rev = "702c74938df48b97370179f33ce2107bd7ff3b3e"
    sha256 = "0hf58ypz6rxsw6nx3i856whir9lvy4sdx946wbw1nfaf2rdmr9vx"

["github.com/nxadm/tail"]
  sumVersion = "v1.4.4"
  ["github.com/nxadm/tail".fetch]
    type = "git"
    url = "https://github.com/nxadm/tail"
    rev = "327c577245448d8192115e77a76ea3d6aee88202"
    sha256 = "1czmwqii0fc8v3ar5bwqpfanprkxg19waly405zlvcflzvj53wwc"

["github.com/onsi/ginkgo"]
  sumVersion = "v1.14.0"
  ["github.com/onsi/ginkgo".fetch]
    type = "git"
    url = "https://github.com/onsi/ginkgo"
    rev = "9c254cb251dc962dc20ca91d0279c870095cfcf9"
    sha256 = "0nwvz0pqk2jqscq88fhppad4flrr8avkxfgbci4xklbar4g8i32v"

["github.com/onsi/gomega"]
  sumVersion = "v1.10.3"
  ["github.com/onsi/gomega".fetch]
    type = "git"
    url = "https://github.com/onsi/gomega"
    rev = "46e0cd22c9d45e5745e994abc67b128504ad7727"
    sha256 = "1jvp5wlny86ncsqak5rz70qfn61y3ajc64w0hrj4840zgh90zb06"

["github.com/pmezard/go-difflib"]
  sumVersion = "v1.0.0"
  ["github.com/pmezard/go-difflib".fetch]
    type = "git"
    url = "https://github.com/pmezard/go-difflib"
    rev = "792786c7400a136282c1664665ae0a8db921c6c2"
    sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw"

["github.com/secure-systems-lab/go-securesystemslib"]
  sumVersion = "v0.3.0"
  ["github.com/secure-systems-lab/go-securesystemslib".fetch]
    type = "git"
    url = "https://github.com/secure-systems-lab/go-securesystemslib"
    rev = "9e1a44e73da822811434596ea22c8200f6e3bbce"
    sha256 = "0f2wr27spnj1mlkx99h29h6mphlmimplvl9wgxnsrjnr7cibkqms"

["github.com/stretchr/objx"]
  sumVersion = "v0.1.0"
  ["github.com/stretchr/objx".fetch]
    type = "git"
    url = "https://github.com/stretchr/objx"
    rev = "facf9a85c22f48d2f52f2380e4efce1768749a89"
    sha256 = "19ynspzjdynbi85xw06mh8ad5j0qa1vryvxjgvbnyrr8rbm4vd8w"

["github.com/stretchr/testify"]
  sumVersion = "v1.7.0"
  ["github.com/stretchr/testify".fetch]
    type = "git"
    url = "https://github.com/stretchr/testify"
    rev = "acba37e5db06f0093b465a7d47822bf13644b66c"
    sha256 = "0ixgjsvafr3513pz3r6pmgk074s2dxkll0dadvl25gkf30rkmh10"

["github.com/syndtr/goleveldb"]
  sumVersion = "v1.0.1-0.20210819022825-2ae1ddf74ef7"
  ["github.com/syndtr/goleveldb".fetch]
    type = "git"
    url = "https://github.com/syndtr/goleveldb"
    rev = "2ae1ddf74ef7020251ff1ff0fe8daac21a157761"
    sha256 = "11b4vjldnp6ws52wlqrzsy6nnn5qa2m98wiqvd90nzsh0n3bi9nz"

["golang.org/x/crypto"]
  sumVersion = "v0.0.0-20211202192323-5770296d904e"
  ["golang.org/x/crypto".fetch]
    type = "git"
    url = "https://go.googlesource.com/crypto"
    rev = "5770296d904e90f15f38f77dfc2e43fdf5efc083"
    sha256 = "16f0ryq9j3jv7af2fnvs08v83i9qhr28hrqwp8z1yyw7xs8qzzf9"

["golang.org/x/net"]
  sumVersion = "v0.0.0-20211209124913-491a49abca63"
  ["golang.org/x/net".fetch]
    type = "git"
    url = "https://go.googlesource.com/net"
    rev = "491a49abca63de5e07ef554052d180a1b5fe2d70"
    sha256 = "14ml2hlwhmafv45lc9wla5y5bcgrmxr2b59sr621ka2r7xmyzhn0"

["golang.org/x/sync"]
  sumVersion = "v0.0.0-20180314180146-1d60e4601c6f"
  ["golang.org/x/sync".fetch]
    type = "git"
    url = "https://go.googlesource.com/sync"
    rev = "1d60e4601c6fd243af51cc01ddf169918a5407ca"
    sha256 = "046jlanz2lkxq1r57x9bl6s4cvfqaic6p2xybsj8mq1120jv4rs6"

["golang.org/x/sys"]
  sumVersion = "v0.0.0-20211205182925-97ca703d548d"
  ["golang.org/x/sys".fetch]
    type = "git"
    url = "https://go.googlesource.com/sys"
    rev = "97ca703d548df069cb02aacea9efc3093ffdc3c4"
    sha256 = "0xhavf3h51zq7d5ckhl77nfvmrzhfv8faqmicc6k03wk91xnj9bg"

["golang.org/x/term"]
  sumVersion = "v0.0.0-20210927222741-03fcf44c2211"
  ["golang.org/x/term".fetch]
    type = "git"
    url = "https://go.googlesource.com/term"
    rev = "03fcf44c2211dcd5eb77510b5f7c1fb02d6ded50"
    sha256 = "0aw5lgwq5w5kvwfa3jl7l83p9c827ksy4a99dqzzsqxvmk2zdi8f"

["golang.org/x/text"]
  sumVersion = "v0.3.7"
  ["golang.org/x/text".fetch]
    type = "git"
    url = "https://go.googlesource.com/text"
    rev = "383b2e75a7a4198c42f8f87833eefb772868a56f"
    sha256 = "0xkw0qvfjyifdqd25y7nxdqkdh92inymw3q7841nricc9s01p4jy"

["golang.org/x/tools"]
  sumVersion = "v0.0.0-20180917221912-90fa682c2a6e"
  ["golang.org/x/tools".fetch]
    type = "git"
    url = "https://go.googlesource.com/tools"
    rev = "90fa682c2a6e6a37b3a1364ce2fe1d5e41af9d6d"
    sha256 = "03ic2xsy51jw9749wl7gszdbz99iijbd2bckgygl6cm9w5m364ak"

["golang.org/x/xerrors"]
  sumVersion = "v0.0.0-20200804184101-5ec99f83aff1"
  ["golang.org/x/xerrors".fetch]
    type = "git"
    url = "https://go.googlesource.com/xerrors"
    rev = "5ec99f83aff198f5fbd629d6c8d8eb38a04218ca"
    sha256 = "1dbzc3gmf2haazpv7cgmv97rq40g2xzwbglc17vas8dwhgwgwrzb"

["google.golang.org/protobuf"]
  sumVersion = "v1.23.0"
  ["google.golang.org/protobuf".fetch]
    type = "git"
    url = "https://go.googlesource.com/protobuf"
    rev = "d165be301fb1e13390ad453281ded24385fd8ebc"
    sha256 = "03yan0m1v0zmlr935p4n24fd376mznsg85zy8sywbgisls4s1bzy"

["gopkg.in/check.v1"]
  sumVersion = "v1.0.0-20201130134442-10cb98267c6c"
  ["gopkg.in/check.v1".fetch]
    type = "git"
    url = "https://gopkg.in/check.v1"
    rev = "10cb98267c6cb43ea9cd6793f29ff4089c306974"
    sha256 = "1jwxndf8rsyx0fgrp47d99rp55yzssmryb92jfj3yf7zd8rjjljn"

["gopkg.in/fsnotify.v1"]
  sumVersion = "v1.4.7"
  ["gopkg.in/fsnotify.v1".fetch]
    type = "git"
    url = "https://gopkg.in/fsnotify.v1"
    rev = "c2828203cd70a50dcccfb2761f8b1f8ceef9a8e9"
    sha256 = "07va9crci0ijlivbb7q57d2rz9h27zgn2fsm60spjsqpdbvyrx4g"

["gopkg.in/tomb.v1"]
  sumVersion = "v1.0.0-20141024135613-dd632973f1e7"
  ["gopkg.in/tomb.v1".fetch]
    type = "git"
    url = "https://gopkg.in/tomb.v1"
    rev = "dd632973f1e7218eb1089048e0798ec9ae7dceb8"
    sha256 = "1lqmq1ag7s4b3gc3ddvr792c5xb5k6sfn0cchr3i2s7f1c231zjv"

["gopkg.in/yaml.v2"]
  sumVersion = "v2.4.0"
  ["gopkg.in/yaml.v2".fetch]
    type = "git"
    url = "https://gopkg.in/yaml.v2"
    rev = "7649d4548cb53a614db133b2a8ac1f31859dda8c"
    sha256 = "1pbmrpj7gcws34g8vwna4i2nhm9p6235piww36436xhyaa10cldr"

["gopkg.in/yaml.v3"]
  sumVersion = "v3.0.0-20210107192922-496545a6307b"
  ["gopkg.in/yaml.v3".fetch]
    type = "git"
    url = "https://gopkg.in/yaml.v3"
    rev = "496545a6307b2a7d7a710fd516e5e16e8ab62dbc"
    sha256 = "06f4lnrp494wqaygv09dggr2dwf3z2bawqhnlnnwiamg5y787k4g"
