["github.com/chzyer/logex"]
  sumVersion = "v1.1.10"
  ["github.com/chzyer/logex".fetch]
    type = "git"
    url = "https://github.com/chzyer/logex"
    rev = "cd112f618178aaaf4ea8592c8839f5276145d9cf"
    sha256 = "08pbjj3wx9acavlwyr055isa8a5hnmllgdv5k6ra60l5y1brmlq4"

["github.com/chzyer/readline"]
  sumVersion = "v0.0.0-20180603132655-2972be24d48e"
  ["github.com/chzyer/readline".fetch]
    type = "git"
    url = "https://github.com/chzyer/readline"
    rev = "2972be24d48e78746da79ba8e24e8b488c9880de"
    sha256 = "104q8dazj8yf6b089jjr82fy9h1g80zyyzvp3g8b44a7d8ngjj6r"

["github.com/chzyer/test"]
  sumVersion = "v0.0.0-20180213035817-a1ea475d72b1"
  ["github.com/chzyer/test".fetch]
    type = "git"
    url = "https://github.com/chzyer/test"
    rev = "a1ea475d72b168a29f44221e0ad031a842642302"
    sha256 = "0rns2aqk22i9xsgyap0pq8wi4cfaxsri4d9q6xxhhyma8jjsnj2k"

["github.com/codahale/rfc6979"]
  sumVersion = "v0.0.0-20141003034818-6a90f24967eb"
  ["github.com/codahale/rfc6979".fetch]
    type = "git"
    url = "https://github.com/codahale/rfc6979"
    rev = "6a90f24967ebb1aa57b22f74a13dbb3faad8cf3d"
    sha256 = "07p51hmvvzvn84mg1c3kmp799j7jf7w15770qw8qz9q7j8frx03f"

["github.com/davecgh/go-spew"]
  sumVersion = "v1.1.1"
  ["github.com/davecgh/go-spew".fetch]
    type = "git"
    url = "https://github.com/davecgh/go-spew"
    rev = "8991bc29aa16c548c550c7ff78260e27b9ab7c73"
    sha256 = "0hka6hmyvp701adzag2g26cxdj47g21x6jz4sc6jjz1mn59d474y"

["github.com/dustin/go-humanize"]
  sumVersion = "v1.0.0"
  ["github.com/dustin/go-humanize".fetch]
    type = "git"
    url = "https://github.com/dustin/go-humanize"
    rev = "9f541cc9db5d55bce703bd99987c9d5cb8eea45e"
    sha256 = "1kqf1kavdyvjk7f8kx62pnm7fbypn9z1vbf8v2qdh3y7z7a0cbl3"

["github.com/flynn/go-docopt"]
  sumVersion = "v0.0.0-20140912013429-f6dd2ebbb31e"
  ["github.com/flynn/go-docopt".fetch]
    type = "git"
    url = "https://github.com/flynn/go-docopt"
    rev = "f6dd2ebbb31e9721c860cf1faf5c944aa73e3844"
    sha256 = "07s8fvnab40mcfmlsgrrddgvrirgm1krb7kaqgipcikjcmj8j6ql"

["github.com/fsnotify/fsnotify"]
  sumVersion = "v1.4.9"
  ["github.com/fsnotify/fsnotify".fetch]
    type = "git"
    url = "https://github.com/fsnotify/fsnotify"
    rev = "45d7d09e39ef4ac08d493309fa031790c15bfe8a"
    sha256 = "1i1r72knpbfwwql9frn9bqc3nhfc2ai5m6qllcyr6wban62lr40x"

["github.com/go-task/slim-sprig"]
  sumVersion = "v0.0.0-20210107165309-348f09dbbbc0"
  ["github.com/go-task/slim-sprig".fetch]
    type = "git"
    url = "https://github.com/go-task/slim-sprig"
    rev = "348f09dbbbc0ff8b922a311da7a90cd014b69aa3"
    sha256 = "16i1w4sm1h8wd132gdaq1z0asj9nc36zs8b3q9jy5kcbjzidl34f"

["github.com/golang/protobuf"]
  sumVersion = "v1.5.2"
  ["github.com/golang/protobuf".fetch]
    type = "git"
    url = "https://github.com/golang/protobuf"
    rev = "ae97035608a719c7a1c1c41bed0ae0744bdb0c6f"
    sha256 = "1mh5fyim42dn821nsd3afnmgscrzzhn3h8rag635d2jnr23r1zhk"

["github.com/golang/snappy"]
  sumVersion = "v0.0.4"
  ["github.com/golang/snappy".fetch]
    type = "git"
    url = "https://github.com/golang/snappy"
    rev = "544b4180ac705b7605231d4a4550a1acb22a19fe"
    sha256 = "004cw699yz3pdpawhjhpa0y94c4w479nw1rf39zj6h6027kpwv2j"

["github.com/google/go-cmp"]
  sumVersion = "v0.5.5"
  ["github.com/google/go-cmp".fetch]
    type = "git"
    url = "https://github.com/google/go-cmp"
    rev = "8fa37b4dd109f12e42b131e485268768f18bcbf8"
    sha256 = "12fmkdhyv5d4is8s57k78j097zb0phlgnrkqc03agiszxlid69x7"

["github.com/google/pprof"]
  sumVersion = "v0.0.0-20210407192527-94a9f03dee38"
  ["github.com/google/pprof".fetch]
    type = "git"
    url = "https://github.com/google/pprof"
    rev = "94a9f03dee38882adc8bdfc42cdd6a04f8e7056e"
    sha256 = "0qx545a5xsfamdbl3x7b149sh0043s377ikhrcdy5rdprs5bbbl3"

["github.com/hpcloud/tail"]
  sumVersion = "v1.0.0"
  ["github.com/hpcloud/tail".fetch]
    type = "git"
    url = "https://github.com/hpcloud/tail"
    rev = "a30252cb686a21eb2d0b98132633053ec2f7f1e5"
    sha256 = "1njpzc0pi1acg5zx9y6vj9xi6ksbsc5d387rd6904hy6rh2m6kn0"

["github.com/ianlancetaylor/demangle"]
  sumVersion = "v0.0.0-20200824232613-28f6c0f3b639"
  ["github.com/ianlancetaylor/demangle".fetch]
    type = "git"
    url = "https://github.com/ianlancetaylor/demangle"
    rev = "28f6c0f3b63983aaa99575ca3b693afff7996387"
    sha256 = "0rsq3622gd40f1x1l7caidsxrmzg1993ich2higwd94fqbxs1r83"

["github.com/kr/pretty"]
  sumVersion = "v0.2.1"
  ["github.com/kr/pretty".fetch]
    type = "git"
    url = "https://github.com/kr/pretty"
    rev = "ead452280cd055b2ae8a7f0db5eb37a878d902f7"
    sha256 = "0vzfz06y9q8gs2nxx0kys0591vzp78k0fvpb8digi5n15h3b25hy"

["github.com/kr/pty"]
  sumVersion = "v1.1.1"
  ["github.com/kr/pty".fetch]
    type = "git"
    url = "https://github.com/kr/pty"
    rev = "282ce0e5322c82529687d609ee670fac7c7d917c"
    sha256 = "0383f0mb9kqjvncqrfpidsf8y6ns5zlrc91c6a74xpyxjwvzl2y6"

["github.com/kr/text"]
  sumVersion = "v0.1.0"
  ["github.com/kr/text".fetch]
    type = "git"
    url = "https://github.com/kr/text"
    rev = "e2ffdb16a802fe2bb95e2e35ff34f0e53aeef34f"
    sha256 = "1gm5bsl01apvc84bw06hasawyqm4q84vx1pm32wr9jnd7a8vjgj1"

["github.com/nxadm/tail"]
  sumVersion = "v1.4.8"
  ["github.com/nxadm/tail".fetch]
    type = "git"
    url = "https://github.com/nxadm/tail"
    rev = "abad231d8d07ef91e09cd4c4c457cac35ed3bbb9"
    sha256 = "1j2gi485fhwdpmyzn42wk62103fclwbfywg42p275z1qv2bsz1rc"

["github.com/onsi/ginkgo"]
  sumVersion = "v1.16.4"
  ["github.com/onsi/ginkgo".fetch]
    type = "git"
    url = "https://github.com/onsi/ginkgo"
    rev = "d125cd027fee341b3b3d65858a4121cf4931fead"
    sha256 = "0rpzh0vg2k33szcq17rdwjvj3q6djp7vqfvasck40gsibadimnd7"

["github.com/onsi/ginkgo/v2"]
  sumVersion = "v2.0.0"
  ["github.com/onsi/ginkgo/v2".fetch]
    type = "git"
    url = "https://github.com/onsi/ginkgo"
    rev = "ae6bc14cee904cc692636afd933fa00e527b9d3a"
    sha256 = "09r83wbkcbvhqn383625zq1w6685k9s5hwmg62ixl1qznpzijw3b"

["github.com/onsi/gomega"]
  sumVersion = "v1.18.1"
  ["github.com/onsi/gomega".fetch]
    type = "git"
    url = "https://github.com/onsi/gomega"
    rev = "d01bc22577e88a1c7afa2448e81ee8e43a598d28"
    sha256 = "0k2y0181a998v55aknp7ph1mhxj1yvw128ilx4bvzb96h8zjk9dp"

["github.com/pmezard/go-difflib"]
  sumVersion = "v1.0.0"
  ["github.com/pmezard/go-difflib".fetch]
    type = "git"
    url = "https://github.com/pmezard/go-difflib"
    rev = "792786c7400a136282c1664665ae0a8db921c6c2"
    sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw"

["github.com/secure-systems-lab/go-securesystemslib"]
  sumVersion = "v0.3.0"
  ["github.com/secure-systems-lab/go-securesystemslib".fetch]
    type = "git"
    url = "https://github.com/secure-systems-lab/go-securesystemslib"
    rev = "9e1a44e73da822811434596ea22c8200f6e3bbce"
    sha256 = "0f2wr27spnj1mlkx99h29h6mphlmimplvl9wgxnsrjnr7cibkqms"

["github.com/stretchr/objx"]
  sumVersion = "v0.1.0"
  ["github.com/stretchr/objx".fetch]
    type = "git"
    url = "https://github.com/stretchr/objx"
    rev = "facf9a85c22f48d2f52f2380e4efce1768749a89"
    sha256 = "19ynspzjdynbi85xw06mh8ad5j0qa1vryvxjgvbnyrr8rbm4vd8w"

["github.com/stretchr/testify"]
  sumVersion = "v1.7.0"
  ["github.com/stretchr/testify".fetch]
    type = "git"
    url = "https://github.com/stretchr/testify"
    rev = "acba37e5db06f0093b465a7d47822bf13644b66c"
    sha256 = "0ixgjsvafr3513pz3r6pmgk074s2dxkll0dadvl25gkf30rkmh10"

["github.com/syndtr/goleveldb"]
  sumVersion = "v1.0.1-0.20210819022825-2ae1ddf74ef7"
  ["github.com/syndtr/goleveldb".fetch]
    type = "git"
    url = "https://github.com/syndtr/goleveldb"
    rev = "2ae1ddf74ef7020251ff1ff0fe8daac21a157761"
    sha256 = "11b4vjldnp6ws52wlqrzsy6nnn5qa2m98wiqvd90nzsh0n3bi9nz"

["github.com/yuin/goldmark"]
  sumVersion = "v1.2.1"
  ["github.com/yuin/goldmark".fetch]
    type = "git"
    url = "https://github.com/yuin/goldmark"
    rev = "91e5269fb0f873f91c9a01e98f32de15ca49440f"
    sha256 = "12rsnsf65drcp0jfw2jl9w589vsn3pxdk1zh3v9q908iigngrcmy"

["golang.org/x/crypto"]
  sumVersion = "v0.0.0-20211117183948-ae814b36b871"
  ["golang.org/x/crypto".fetch]
    type = "git"
    url = "https://go.googlesource.com/crypto"
    rev = "ae814b36b87190c757eede9bc2d32ed77df88551"
    sha256 = "01d5llpsijgbgm8px6mhaknqwh8g707zc5i5744gcndr8w0649sk"

["golang.org/x/mod"]
  sumVersion = "v0.3.0"
  ["golang.org/x/mod".fetch]
    type = "git"
    url = "https://go.googlesource.com/mod"
    rev = "859b3ef565e237f9f1a0fb6b55385c497545680d"
    sha256 = "0ldgbx2zpprbsfn6p8pfgs4nn87gwbfcv2z0fa7n8alwsq2yw78q"

["golang.org/x/net"]
  sumVersion = "v0.0.0-20220127200216-cd36cc0744dd"
  ["golang.org/x/net".fetch]
    type = "git"
    url = "https://go.googlesource.com/net"
    rev = "cd36cc0744dd695657988f15f08446dc81e16efc"
    sha256 = "1gkddgbhl0hkx79y31pfr2a7qc1wnviwmzfzh722sngck0cqd61h"

["golang.org/x/sync"]
  sumVersion = "v0.0.0-20201020160332-67f06af15bc9"
  ["golang.org/x/sync".fetch]
    type = "git"
    url = "https://go.googlesource.com/sync"
    rev = "67f06af15bc961c363a7260195bcd53487529a21"
    sha256 = "093p4panc808ak5bamzz7m9nb0xxib7778jpnr6f0xkz1n4fzyw5"

["golang.org/x/sys"]
  sumVersion = "v0.0.0-20211216021012-1d35b9e2eb4e"
  ["golang.org/x/sys".fetch]
    type = "git"
    url = "https://go.googlesource.com/sys"
    rev = "1d35b9e2eb4edf581781c7f3e2a36fac701f0a24"
    sha256 = "09xmnw6hhpqnakm99xxigg0znbx46f084lpacz67p5rbcdngjxis"

["golang.org/x/term"]
  sumVersion = "v0.0.0-20210927222741-03fcf44c2211"
  ["golang.org/x/term".fetch]
    type = "git"
    url = "https://go.googlesource.com/term"
    rev = "03fcf44c2211dcd5eb77510b5f7c1fb02d6ded50"
    sha256 = "0aw5lgwq5w5kvwfa3jl7l83p9c827ksy4a99dqzzsqxvmk2zdi8f"

["golang.org/x/text"]
  sumVersion = "v0.3.7"
  ["golang.org/x/text".fetch]
    type = "git"
    url = "https://go.googlesource.com/text"
    rev = "383b2e75a7a4198c42f8f87833eefb772868a56f"
    sha256 = "0xkw0qvfjyifdqd25y7nxdqkdh92inymw3q7841nricc9s01p4jy"

["golang.org/x/tools"]
  sumVersion = "v0.0.0-20201224043029-2b0845dc783e"
  ["golang.org/x/tools".fetch]
    type = "git"
    url = "https://go.googlesource.com/tools"
    rev = "2b0845dc783e36ae26d683f4915a5840ef01ab0f"
    sha256 = "1hn6rbmyhdxfff56iz16yvaxzp6xzz9bc49h106v8rh78iclh7kc"

["golang.org/x/xerrors"]
  sumVersion = "v0.0.0-20200804184101-5ec99f83aff1"
  ["golang.org/x/xerrors".fetch]
    type = "git"
    url = "https://go.googlesource.com/xerrors"
    rev = "5ec99f83aff198f5fbd629d6c8d8eb38a04218ca"
    sha256 = "1dbzc3gmf2haazpv7cgmv97rq40g2xzwbglc17vas8dwhgwgwrzb"

["google.golang.org/protobuf"]
  sumVersion = "v1.26.0"
  ["google.golang.org/protobuf".fetch]
    type = "git"
    url = "https://go.googlesource.com/protobuf"
    rev = "f2d1f6cbe10b90d22296ea09a7217081c2798009"
    sha256 = "0xq6phaps6d0vcv13ga59gzj4306l0ki9kikhmb52h6pq0iwfqlz"

["gopkg.in/check.v1"]
  sumVersion = "v1.0.0-20201130134442-10cb98267c6c"
  ["gopkg.in/check.v1".fetch]
    type = "git"
    url = "https://gopkg.in/check.v1"
    rev = "10cb98267c6cb43ea9cd6793f29ff4089c306974"
    sha256 = "1jwxndf8rsyx0fgrp47d99rp55yzssmryb92jfj3yf7zd8rjjljn"

["gopkg.in/fsnotify.v1"]
  sumVersion = "v1.4.7"
  ["gopkg.in/fsnotify.v1".fetch]
    type = "git"
    url = "https://gopkg.in/fsnotify.v1"
    rev = "c2828203cd70a50dcccfb2761f8b1f8ceef9a8e9"
    sha256 = "07va9crci0ijlivbb7q57d2rz9h27zgn2fsm60spjsqpdbvyrx4g"

["gopkg.in/tomb.v1"]
  sumVersion = "v1.0.0-20141024135613-dd632973f1e7"
  ["gopkg.in/tomb.v1".fetch]
    type = "git"
    url = "https://gopkg.in/tomb.v1"
    rev = "dd632973f1e7218eb1089048e0798ec9ae7dceb8"
    sha256 = "1lqmq1ag7s4b3gc3ddvr792c5xb5k6sfn0cchr3i2s7f1c231zjv"

["gopkg.in/yaml.v2"]
  sumVersion = "v2.4.0"
  ["gopkg.in/yaml.v2".fetch]
    type = "git"
    url = "https://gopkg.in/yaml.v2"
    rev = "7649d4548cb53a614db133b2a8ac1f31859dda8c"
    sha256 = "1pbmrpj7gcws34g8vwna4i2nhm9p6235piww36436xhyaa10cldr"

["gopkg.in/yaml.v3"]
  sumVersion = "v3.0.0-20200313102051-9f266ea9e77c"
  ["gopkg.in/yaml.v3".fetch]
    type = "git"
    url = "https://gopkg.in/yaml.v3"
    rev = "9f266ea9e77c4c7aab4cf02650570e7c7b3031a5"
    sha256 = "1bbai3lzb50m0x2vwsdbagrbhvfylj9k1m32hgbqwldqx4p9ay35"
